
debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    # root ??? ?? log? debug? ??? ??? ???? ???? ? ??
    org.board.boardproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/junjunDB
    username: junjun
    password: junjun
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  application:
---
episodeImgLocation: /Users/yunseongjun/programming/Project/ImgFIle/episode
uploadPath: file:/Users/yunseongjun/programming/Project/ImgFIle/
---
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  # h2 console url connect false -> true change
  h2.console.enabled: false
  sql.init.mode: always
#  data.rest:
#    base-path: /api
#    detection-strategy: annotated
---